### ISSUE TITLE
Add Primary Constructor and Secondary Constructor in Kotlin

### ISSUE THREAD

**Issue by PrajjawalBanati** [PrajjawalBanati/Kotlin_Language#11]
Make a program and show a difference between primary and secondary constructors in kotlin. Also write which constructors gets called first and next

**Comment by jalalkhademi** [comment]
Sounds an interesting project. May I work on this?

**Comment by PrajjawalBanati** [comment]
Yeah Sure !!! Go on and after you had done just make a pull request and after reviewing I will merge it.
