### ISSUE TITLE
OOPs in Kotlin 

### ISSUE THREAD

**Issue by PrajjawalBanati** [PrajjawalBanati/Kotlin_Language#12]
Make 4 different programs following 4 different OOPs concepts. Note that include all the 4 programs in one project(Folder) only.

**Comment by hannahlspencer** [comment]
I can help with that! Just to confirm: Abstraction, Encapsulation, Inheritance, and Polymorphism?

**Comment by PrajjawalBanati** [comment]
Yes !! @hannahlspencer
